version: "3"
services:
    php:
        build:
            context: ../..
            dockerfile: docker/local/php/Dockerfile
        container_name: test-lara-app
        hostname: test-lara-app
        restart: unless-stopped
        ports:
            - '8080:8080'
        volumes:
            - ../../:/var/www
        networks:
            - test-lara

    db:
        image: postgres:latest
        container_name: test-lara-db
        hostname: test-lara-db
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: $DATABASE_PASSWORD
            POSTGRES_USER: $DATABASE_USER
            POSTGRES_DB: $DATABASE_NAME
        volumes:
            - db_lara_data:/var/lib/postgresql/data:rw
        ports:
            - '${DATABASE_PORT}:5432'
        networks:
            - test-lara


volumes:
    db_lara_data:

networks:
    test-lara:
        driver: bridge

